export const quotes = [
  // Miyamoto Musashi
  { author: "Miyamoto Musashi", text: "Accept everything just the way it is." },
  { author: "Miyamoto Musashi", text: "Think lightly of yourself and deeply of the world." },
  { author: "Miyamoto Musashi", text: "Do not regret what you have done." },
  { author: "Miyamoto Musashi", text: "Perceive that which cannot be seen with the eye." },
  { author: "Miyamoto Musashi", text: "Today is victory over yourself of yesterday." },
  { author: "Miyamoto Musashi", text: "You must understand there is more than one path to the top of the mountain." },
  { author: "Miyamoto Musashi", text: "From one thing, know ten thousand things." },
  { author: "Miyamoto Musashi", text: "The ultimate aim of martial arts is not having to use them." },
  { author: "Miyamoto Musashi", text: "Do nothing which is of no use." },
  { author: "Miyamoto Musashi", text: "Respect Buddha and the gods without counting on their help." },
  { author: "Miyamoto Musashi", text: "Never stray from the Way." },
  { author: "Miyamoto Musashi", text: "You can only fight the way you practice." },
  { author: "Miyamoto Musashi", text: "It is difficult to understand the universe if you only study one planet." },
  { author: "Miyamoto Musashi", text: "Do not let the body be dragged by the mind." },
  { author: "Miyamoto Musashi", text: "Do not hold on to possessions you no longer need." },
  { author: "Miyamoto Musashi", text: "Do not seek pleasure for its own sake." },
  { author: "Miyamoto Musashi", text: "Do not act following customary beliefs." },
  { author: "Miyamoto Musashi", text: "Do not collect weapons beyond what is useful." },
  { author: "Miyamoto Musashi", text: "Do not fear death." },
  { author: "Miyamoto Musashi", text: "Do not pursue the taste of good food." },
  { author: "Miyamoto Musashi", text: "Train every day." },
  { author: "Miyamoto Musashi", text: "Observe carefully." },
  { author: "Miyamoto Musashi", text: "See what cannot be seen." },
  { author: "Miyamoto Musashi", text: "Know the smallest things and the biggest things." },
  { author: "Miyamoto Musashi", text: "Timing is everything." },
  { author: "Miyamoto Musashi", text: "Study strategy over many years." },
  { author: "Miyamoto Musashi", text: "The Way is in training." },
  { author: "Miyamoto Musashi", text: "Understand your enemy and yourself." },
  { author: "Miyamoto Musashi", text: "Empty your mind of distractions." },
  { author: "Miyamoto Musashi", text: "Master yourself before seeking to master others." },
  // Added: Dokkodo (The Path of Aloneness)
  { author: "Miyamoto Musashi", text: "Do not, under any circumstances, depend on a partial feeling." },
  { author: "Miyamoto Musashi", text: "Be detached from desire your whole life long." },
  { author: "Miyamoto Musashi", text: "Never be jealous." },
  { author: "Miyamoto Musashi", text: "Never let yourself be saddened by a separation." },
  { author: "Miyamoto Musashi", text: "Resentment and complaint are appropriate neither for oneself nor for others." },
  { author: "Miyamoto Musashi", text: "In all things, have no preferences." },
  { author: "Miyamoto Musashi", text: "Be indifferent to where you live." },
  { author: "Miyamoto Musashi", text: "Do not seek to possess goods or lands for your old age." },
  { author: "Miyamoto Musashi", text: "You may abandon your own body, but you must preserve your honor." },
  // Added: Go Rin No Sho (The Book of Five Rings)
  { author: "Miyamoto Musashi", text: "Do not think dishonestly." },
  { author: "Miyamoto Musashi", text: "Become acquainted with every art." },
  { author: "Miyamoto Musashi", text: "Know the ways of all professions." },
  { author: "Miyamoto Musashi", text: "Distinguish between gain and loss in worldly matters." },
  { author: "Miyamoto Musashi", text: "Develop intuitive judgment and understanding for everything." },
  { author: "Miyamoto Musashi", text: "Pay attention even to trifles." },
  { author: "Miyamoto Musashi", text: "Step by step, walk the thousand-mile road." },
  { author: "Miyamoto Musashi", text: "A thousand days of training to forge, ten thousand days to polish." },
  { author: "Miyamoto Musashi", text: "If you know the Way broadly, you will see it in all things." },
  { author: "Miyamoto Musashi", text: "See distant things as if they were close, and take a distanced view of close things." },
  { author: "Miyamoto Musashi", text: "Perception is strong and sight is weak." },
  { author: "Miyamoto Musashi", text: "You should not have a favorite weapon." },
  { author: "Miyamoto Musashi", text: "In fighting and in everyday life, be determined yet calm." },
  { author: "Miyamoto Musashi", text: "Become the enemy." },

  // Napoleon Bonaparte
  { author: "Napoleon Bonaparte", text: "Impossible is a word to be found only in the dictionary of fools." },
  { author: "Napoleon Bonaparte", text: "Victory belongs to the most persevering." },
  { author: "Napoleon Bonaparte", text: "A leader is a dealer in hope." },
  { author: "Napoleon Bonaparte", text: "Ability is nothing without opportunity." },
  { author: "Napoleon Bonaparte", text: "Take time to deliberate, but when the time for action arrives, stop thinking and go in." },
  { author: "Napoleon Bonaparte", text: "History is a set of lies agreed upon." },
  { author: "Napoleon Bonaparte", text: "Courage is going from failure to failure without losing enthusiasm." },
  { author: "Napoleon Bonaparte", text: "If you want a thing done well, do it yourself." },
  { author: "Napoleon Bonaparte", text: "Men are moved by fear and self-interest." },
  { author: "Napoleon Bonaparte", text: "Never interrupt your enemy when he is making a mistake." },
  { author: "Napoleon Bonaparte", text: "Death is nothing, but to live defeated is to die every day." },
  { author: "Napoleon Bonaparte", text: "Ten people who speak make more noise than ten thousand who are silent." },
  { author: "Napoleon Bonaparte", text: "Imagination rules the world." },
  { author: "Napoleon Bonaparte", text: "Great ambition is the passion of a great character." },
  { author: "Napoleon Bonaparte", text: "Religion is excellent stuff for keeping common people quiet." },
  { author: "Napoleon Bonaparte", text: "The battlefield is a scene of chaos." },
  { author: "Napoleon Bonaparte", text: "The strong man controls the communication between senses and mind." },
  { author: "Napoleon Bonaparte", text: "Riches do not consist in possession, but in use." },
  { author: "Napoleon Bonaparte", text: "Four hostile newspapers are more feared than a thousand bayonets." },
  { author: "Napoleon Bonaparte", text: "Glory is fleeting, but obscurity is forever." },
  { author: "Napoleon Bonaparte", text: "Power is my mistress." },
  { author: "Napoleon Bonaparte", text: "Nothing is more difficult than making decisions." },
  { author: "Napoleon Bonaparte", text: "A throne is merely a bench covered with velvet." },
  { author: "Napoleon Bonaparte", text: "One must change tactics every ten years." },
  { author: "Napoleon Bonaparte", text: "In war, moral force outweighs physical force." },
  { author: "Napoleon Bonaparte", text: "Great men are meteors designed to burn." },
  { author: "Napoleon Bonaparte", text: "Success is the most convincing speaker." },
  { author: "Napoleon Bonaparte", text: "Opportunity is often disguised as hardship." },
  { author: "Napoleon Bonaparte", text: "The best cure for the body is a quiet mind." },
  { author: "Napoleon Bonaparte", text: "Audacity often wins where caution fails." },
  // Added
  { author: "Napoleon Bonaparte", text: "An army marches on its stomach." },
  { author: "Napoleon Bonaparte", text: "The word impossible is not French." },
  { author: "Napoleon Bonaparte", text: "From the sublime to the ridiculous there is only one step." },
  { author: "Napoleon Bonaparte", text: "There are only two forces in the world, the sword and the spirit. In the long run, the sword will always be conquered by the spirit." },
  { author: "Napoleon Bonaparte", text: "What is history but a fable agreed upon?" },
  { author: "Napoleon Bonaparte", text: "Soldiers usually win the battles, and generals get the credit for them." },
  { author: "Napoleon Bonaparte", text: "A soldier will fight long and hard for a bit of colored ribbon." },
  { author: "Napoleon Bonaparte", text: "Every French soldier carries a marshal's baton in his knapsack." },
  { author: "Napoleon Bonaparte", text: "I am sometimes a fox and sometimes a lion. The whole secret of government lies in knowing when to be one or the other." },
  { author: "Napoleon Bonaparte", text: "Men are more easily governed through their vices than through their virtues." },
  { author: "Napoleon Bonaparte", text: "The torment of precautions often exceeds the dangers to be avoided." },
  { author: "Napoleon Bonaparte", text: "Space we can recover; time, never." },
  { author: "Napoleon Bonaparte", text: "An order that can be misunderstood will be misunderstood." },
  { author: "Napoleon Bonaparte", text: "Unhappy the general who comes onto the field of battle with a system." },
  { author: "Napoleon Bonaparte", text: "The policy of a state lies in its geography." },
  { author: "Napoleon Bonaparte", text: "Public opinion is the thermometer a monarch should constantly consult." },
  { author: "Napoleon Bonaparte", text: "Conquest has made me what I am; conquest alone can maintain me." },
  { author: "Napoleon Bonaparte", text: "The fool has one great advantage over a man of sense: he is always satisfied with himself." },
  { author: "Napoleon Bonaparte", text: "Water, air, and cleanliness are the chief articles in my pharmacy." },
  { author: "Napoleon Bonaparte", text: "The truest wisdom is a resolute determination." },
  { author: "Napoleon Bonaparte", text: "What a novel my life has been!" },

  // Marcus Aurelius
  { author: "Marcus Aurelius", text: "You have power over your mind, not outside events." },
  { author: "Marcus Aurelius", text: "The happiness of your life depends upon the quality of your thoughts." },
  { author: "Marcus Aurelius", text: "Waste no more time arguing what a good man should be. Be one." },
  { author: "Marcus Aurelius", text: "The best revenge is not to be like your enemy." },
  { author: "Marcus Aurelius", text: "The soul becomes dyed with the color of its thoughts." },
  { author: "Marcus Aurelius", text: "Confine yourself to the present." },
  { author: "Marcus Aurelius", text: "Our life is what our thoughts make it." },
  { author: "Marcus Aurelius", text: "If it is not right, do not do it." },
  { author: "Marcus Aurelius", text: "If it is not true, do not say it." },
  { author: "Marcus Aurelius", text: "Very little is needed for a happy life." },
  { author: "Marcus Aurelius", text: "Choose not to be harmed and you won't feel harmed." },
  { author: "Marcus Aurelius", text: "Do every act as if it were your last." },
  { author: "Marcus Aurelius", text: "Look inward." },
  { author: "Marcus Aurelius", text: "Accept what fate brings." },
  { author: "Marcus Aurelius", text: "Death smiles at us all." },
  { author: "Marcus Aurelius", text: "Dwell on the beauty of life." },
  { author: "Marcus Aurelius", text: "Everything we hear is an opinion." },
  { author: "Marcus Aurelius", text: "Everything we see is a perspective." },
  { author: "Marcus Aurelius", text: "The obstacle becomes the way." },
  { author: "Marcus Aurelius", text: "When you wake up, be grateful to be alive." },
  { author: "Marcus Aurelius", text: "Be tolerant with others and strict with yourself." },
  { author: "Marcus Aurelius", text: "Nothing happens to anyone that he cannot endure." },
  { author: "Marcus Aurelius", text: "What stands in the way becomes the way." },
  { author: "Marcus Aurelius", text: "Loss is nothing but change." },
  { author: "Marcus Aurelius", text: "The universe is change." },
  { author: "Marcus Aurelius", text: "Do not fear death." },
  { author: "Marcus Aurelius", text: "Seek truth." },
  { author: "Marcus Aurelius", text: "Live according to nature." },
  { author: "Marcus Aurelius", text: "Be good while you can." },
  { author: "Marcus Aurelius", text: "The present moment is enough." },
  // Added: Meditations
  { author: "Marcus Aurelius", text: "Look within. Within is the fountain of good." },
  { author: "Marcus Aurelius", text: "The art of living is more like wrestling than dancing." },
  { author: "Marcus Aurelius", text: "Be like the headland on which the waves continually break." },
  { author: "Marcus Aurelius", text: "Do not act as if you were going to live ten thousand years." },
  { author: "Marcus Aurelius", text: "Time is a river of passing events, and strong is its current." },
  { author: "Marcus Aurelius", text: "Whatever happens, happens as it should." },
  { author: "Marcus Aurelius", text: "Take away your opinion, and the complaint is taken away." },
  { author: "Marcus Aurelius", text: "Reject your sense of injury and the injury itself disappears." },
  { author: "Marcus Aurelius", text: "How much more grievous are the consequences of anger than its causes." },
  { author: "Marcus Aurelius", text: "What is not good for the swarm is not good for the bee." },
  { author: "Marcus Aurelius", text: "Men exist for the sake of one another." },
  { author: "Marcus Aurelius", text: "Nowhere can a man find a quieter retreat than in his own soul." },
  { author: "Marcus Aurelius", text: "Adapt yourself to the things among which your lot has been cast." },
  { author: "Marcus Aurelius", text: "Everything is only for a day, both that which remembers and that which is remembered." },
  { author: "Marcus Aurelius", text: "Alexander the Great and his mule driver both died, and the same thing happened to both." },
  { author: "Marcus Aurelius", text: "If someone can show me that I think or act wrongly, I will gladly change." },
  { author: "Marcus Aurelius", text: "Stand upright, not held upright." },
  { author: "Marcus Aurelius", text: "Short is the life that remains to you. Live as on a mountain." },
  { author: "Marcus Aurelius", text: "Never value anything that makes you break your word or lose your self-respect." },
  { author: "Marcus Aurelius", text: "Receive without pride, let go without struggle." },
  { author: "Marcus Aurelius", text: "You could leave life right now. Let that determine what you do and say and think." },
  { author: "Marcus Aurelius", text: "The nearer a man comes to a calm mind, the closer he is to strength." },

  // Seneca
  { author: "Seneca", text: "We suffer more often in imagination than in reality." },
  { author: "Seneca", text: "It is not that we have a short time to live, but that we waste much of it." },
  { author: "Seneca", text: "Luck is what happens when preparation meets opportunity." },
  { author: "Seneca", text: "Difficulties strengthen the mind as labor strengthens the body." },
  { author: "Seneca", text: "He who is brave is free." },
  { author: "Seneca", text: "No man was ever wise by chance." },
  { author: "Seneca", text: "The greatest wealth is a poverty of desires." },
  { author: "Seneca", text: "Wherever there is a human being, there is an opportunity for kindness." },
  { author: "Seneca", text: "Associate with people who make you better." },
  { author: "Seneca", text: "Fire tests gold; adversity tests men." },
  { author: "Seneca", text: "As long as you live, keep learning." },
  { author: "Seneca", text: "True happiness is to enjoy the present." },
  { author: "Seneca", text: "Time discovers truth." },
  { author: "Seneca", text: "Nothing is ours except time." },
  { author: "Seneca", text: "Begin at once to live." },
  { author: "Seneca", text: "A gem cannot be polished without friction." },
  { author: "Seneca", text: "A man who suffers before necessary suffers more than necessary." },
  { author: "Seneca", text: "Fate leads the willing and drags the unwilling." },
  { author: "Seneca", text: "No wind is favorable to the sailor without a destination." },
  { author: "Seneca", text: "Life is long if you know how to use it." },
  { author: "Seneca", text: "Anger is temporary madness." },
  { author: "Seneca", text: "Every day is a complete life." },
  { author: "Seneca", text: "The wise man is content with himself." },
  { author: "Seneca", text: "Leisure without study is death." },
  { author: "Seneca", text: "He lives badly who does not know how to die well." },
  { author: "Seneca", text: "Poverty is not having too little but desiring more." },
  { author: "Seneca", text: "Great blessings bring great worries." },
  { author: "Seneca", text: "To be everywhere is to be nowhere." },
  { author: "Seneca", text: "The whole future lies in uncertainty; live immediately." },
  // Added: Letters, On the Shortness of Life, On Anger
  { author: "Seneca", text: "While we are postponing, life speeds by." },
  { author: "Seneca", text: "Hold every hour in your grasp." },
  { author: "Seneca", text: "Most powerful is he who has himself in his own power." },
  { author: "Seneca", text: "Sometimes even to live is an act of courage." },
  { author: "Seneca", text: "Whatever can happen at any time can happen today." },
  { author: "Seneca", text: "The mind that is anxious about the future is miserable." },
  { author: "Seneca", text: "A great fortune is a great slavery." },
  { author: "Seneca", text: "Wealth is the slave of a wise man and the master of a fool." },
  { author: "Seneca", text: "Fortune does not give; it only lends." },
  { author: "Seneca", text: "Men learn while they teach." },
  { author: "Seneca", text: "The road by precept is long; by example, short and effective." },
  { author: "Seneca", text: "What bad habit have you cured today?" },
  { author: "Seneca", text: "Other men's sins are before our eyes; our own are behind our backs." },
  { author: "Seneca", text: "There is no great genius without a touch of madness." },
  { author: "Seneca", text: "The part of life we truly live is small." },
  { author: "Seneca", text: "Life, if well lived, is long enough." },
  { author: "Seneca", text: "Retire into yourself as much as you can." },
  { author: "Seneca", text: "You must live for another if you wish to live for yourself." },
  { author: "Seneca", text: "Show me a man who is not a slave." },
  { author: "Seneca", text: "Only time can heal what reason cannot." },
  { author: "Seneca", text: "No evil is without its compensation." }
];